### ISSUE TITLE
Corrigir erros com tema Divi Ecommerce

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/wc_cielo_payment_gateway#76]
Quando habilitamos o tema Divi Ecommerce com o plugin de faturas os erros não são exibidos e o plugin não conclui o pagamento, o JS da animação do cartão também parece não estar funcionando.

**Comment by emanuellopess** [comment]
@GuilhermeLinkNacional Problemas de tipagem possívelmente

logs resumidos:
```
2024-07-24T16:22:35+00:00 Crítico Uncaught TypeError: Unsupported operand types: string * int in /home/linknacional/paraquemdoar.org/wp-content/plugins/lkn-wc-gateway-cielo/includes/LknWCGatewayCieloCredit.php:637
Contexto adicional
2024-07-24T16:22:43+00:00 Crítico Uncaught TypeError: Unsupported operand types: string * int in /home/linknacional/paraquemdoar.org/wp-content/plugins/lkn-wc-gateway-cielo/includes/LknWCGatewayCieloCredit.php:637
Contexto adicional
2024-07-24T16:23:07+00:00 Crítico Uncaught TypeError: Unsupported operand types: string * int in /home/linknacional/paraquemdoar.org/wp-content/plugins/lkn-wc-gateway-cielo/includes/LknWCGatewayCieloCredit.php:637
Contexto adicional
2024-07-24T18:30:09+00:00 Crítico Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/StoreApi/Legacy.php:67
```

logs detalhados:
```
2024-07-24T16:22:35+00:00 CRITICAL Uncaught TypeError: Unsupported operand types: string * int in /home/linknacional/paraquemdoar.org/wp-content/plugins/lkn-wc-gateway-cielo/includes/LknWCGatewayCieloCredit.php:637 CONTEXT: {"error":{"type":1,"file":"/home/linknacional/paraquemdoar.org/wp-content/plugins/lkn-wc-gateway-cielo/includes/LknWCGatewayCieloCredit.php","line":637},"backtrace":["","#0 /home/linknacional/paraquemdoar.org/wp-content/plugins/lkn-wc-gateway-cielo/includes/LknWcCieloCreditBlocks.php(48): Lkn\WCCieloPaymentGateway\Includes\LknWCGatewayCieloCredit::lknGetCartTotal()","#1 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/Payments/PaymentMethodRegistry.php(62): Lkn\WCCieloPaymentGateway\Includes\LknWcCieloCreditBlocks->get_payment_method_data()","#2 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/Payments/Api.php(92): Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->get_all_registered_script_data()","#3 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Blocks\Payments\Api->add_payment_method_script_data()","#4 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()","#5 /home/linknacional/paraquemdoar.org/wp-includes/plugin.php(517): WP_Hook->do_action()","#6 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php(456): do_action()","#7 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php(416): Automattic\WooCommerce\Blocks\BlockTypes\Checkout->enqueue_data()","#8 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php(128): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_assets()","#9 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php(96): Automattic\WooCommerce\Blocks\BlockTypes\Checkout->enqueue_assets()","#10 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-block.php(519): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback()","#11 /home/linknacional/paraquemdoar.org/wp-includes/blocks.php(2061): WP_Block->render()","#12 /home/linknacional/paraquemdoar.org/wp-includes/blocks.php(2113): render_block()","#13 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-hook.php(324): do_blocks()","#14 /home/linknacional/paraquemdoar.org/wp-includes/plugin.php(205): WP_Hook->apply_filters()","#15 /home/linknacional/paraquemdoar.org/wp-includes/post-template.php(256): apply_filters()","#16 /home/linknacional/paraquemdoar.org/wp-content/themes/qizon/templates/page/single.php(44): the_content()","#17 /home/linknacional/paraquemdoar.org/wp-includes/template.php(812): require('/home/linknacio...')","#18 /home/linknacional/paraquemdoar.org/wp-includes/template.php(745): load_template()","#19 /home/linknacional/paraquemdoar.org/wp-includes/general-template.php(206): locate_template()","#20 /home/linknacional/paraquemdoar.org/wp-content/themes/qizon/page.php(23): get_template_part()","#21 /home/linknacional/paraquemdoar.org/wp-includes/template-loader.php(106): include('/home/linknacio...')","#22 /home/linknacional/paraquemdoar.org/wp-blog-header.php(19): require_once('/home/linknacio...')","#23 /home/linknacional/paraquemdoar.org/index.php(17): require('/home/linknacio...')","#24 {main}","thrown"]}
2024-07-24T16:22:43+00:00 CRITICAL Uncaught TypeError: Unsupported operand types: string * int in /home/linknacional/paraquemdoar.org/wp-content/plugins/lkn-wc-gateway-cielo/includes/LknWCGatewayCieloCredit.php:637 CONTEXT: {"error":{"type":1,"file":"/home/linknacional/paraquemdoar.org/wp-content/plugins/lkn-wc-gateway-cielo/includes/LknWCGatewayCieloCredit.php","line":637},"backtrace":["","#0 /home/linknacional/paraquemdoar.org/wp-content/plugins/lkn-wc-gateway-cielo/includes/LknWcCieloCreditBlocks.php(48): Lkn\WCCieloPaymentGateway\Includes\LknWCGatewayCieloCredit::lknGetCartTotal()","#1 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/Payments/PaymentMethodRegistry.php(62): Lkn\WCCieloPaymentGateway\Includes\LknWcCieloCreditBlocks->get_payment_method_data()","#2 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/Payments/Api.php(92): Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->get_all_registered_script_data()","#3 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Blocks\Payments\Api->add_payment_method_script_data()","#4 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()","#5 /home/linknacional/paraquemdoar.org/wp-includes/plugin.php(517): WP_Hook->do_action()","#6 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php(456): do_action()","#7 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php(416): Automattic\WooCommerce\Blocks\BlockTypes\Checkout->enqueue_data()","#8 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php(128): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_assets()","#9 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php(96): Automattic\WooCommerce\Blocks\BlockTypes\Checkout->enqueue_assets()","#10 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-block.php(519): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback()","#11 /home/linknacional/paraquemdoar.org/wp-includes/blocks.php(2061): WP_Block->render()","#12 /home/linknacional/paraquemdoar.org/wp-includes/blocks.php(2113): render_block()","#13 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-hook.php(324): do_blocks()","#14 /home/linknacional/paraquemdoar.org/wp-includes/plugin.php(205): WP_Hook->apply_filters()","#15 /home/linknacional/paraquemdoar.org/wp-includes/post-template.php(256): apply_filters()","#16 /home/linknacional/paraquemdoar.org/wp-content/themes/qizon/templates/page/single.php(44): the_content()","#17 /home/linknacional/paraquemdoar.org/wp-includes/template.php(812): require('/home/linknacio...')","#18 /home/linknacional/paraquemdoar.org/wp-includes/template.php(745): load_template()","#19 /home/linknacional/paraquemdoar.org/wp-includes/general-template.php(206): locate_template()","#20 /home/linknacional/paraquemdoar.org/wp-content/themes/qizon/page.php(23): get_template_part()","#21 /home/linknacional/paraquemdoar.org/wp-includes/template-loader.php(106): include('/home/linknacio...')","#22 /home/linknacional/paraquemdoar.org/wp-blog-header.php(19): require_once('/home/linknacio...')","#23 /home/linknacional/paraquemdoar.org/index.php(17): require('/home/linknacio...')","#24 {main}","thrown"]}
2024-07-24T16:23:07+00:00 CRITICAL Uncaught TypeError: Unsupported operand types: string * int in /home/linknacional/paraquemdoar.org/wp-content/plugins/lkn-wc-gateway-cielo/includes/LknWCGatewayCieloCredit.php:637 CONTEXT: {"error":{"type":1,"file":"/home/linknacional/paraquemdoar.org/wp-content/plugins/lkn-wc-gateway-cielo/includes/LknWCGatewayCieloCredit.php","line":637},"backtrace":["","#0 /home/linknacional/paraquemdoar.org/wp-content/plugins/lkn-wc-gateway-cielo/includes/LknWcCieloCreditBlocks.php(48): Lkn\WCCieloPaymentGateway\Includes\LknWCGatewayCieloCredit::lknGetCartTotal()","#1 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/Payments/PaymentMethodRegistry.php(62): Lkn\WCCieloPaymentGateway\Includes\LknWcCieloCreditBlocks->get_payment_method_data()","#2 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/Payments/Api.php(92): Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->get_all_registered_script_data()","#3 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Blocks\Payments\Api->add_payment_method_script_data()","#4 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()","#5 /home/linknacional/paraquemdoar.org/wp-includes/plugin.php(517): WP_Hook->do_action()","#6 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php(456): do_action()","#7 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php(416): Automattic\WooCommerce\Blocks\BlockTypes\Checkout->enqueue_data()","#8 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/Checkout.php(128): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_assets()","#9 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/Blocks/BlockTypes/AbstractBlock.php(96): Automattic\WooCommerce\Blocks\BlockTypes\Checkout->enqueue_assets()","#10 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-block.php(519): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback()","#11 /home/linknacional/paraquemdoar.org/wp-includes/blocks.php(2061): WP_Block->render()","#12 /home/linknacional/paraquemdoar.org/wp-includes/blocks.php(2113): render_block()","#13 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-hook.php(324): do_blocks()","#14 /home/linknacional/paraquemdoar.org/wp-includes/plugin.php(205): WP_Hook->apply_filters()","#15 /home/linknacional/paraquemdoar.org/wp-includes/post-template.php(256): apply_filters()","#16 /home/linknacional/paraquemdoar.org/wp-content/themes/qizon/templates/page/single.php(44): the_content()","#17 /home/linknacional/paraquemdoar.org/wp-includes/template.php(812): require('/home/linknacio...')","#18 /home/linknacional/paraquemdoar.org/wp-includes/template.php(745): load_template()","#19 /home/linknacional/paraquemdoar.org/wp-includes/general-template.php(206): locate_template()","#20 /home/linknacional/paraquemdoar.org/wp-content/themes/qizon/page.php(23): get_template_part()","#21 /home/linknacional/paraquemdoar.org/wp-includes/template-loader.php(106): include('/home/linknacio...')","#22 /home/linknacional/paraquemdoar.org/wp-blog-header.php(19): require_once('/home/linknacio...')","#23 /home/linknacional/paraquemdoar.org/index.php(17): require('/home/linknacio...')","#24 {main}","thrown"]}
2024-07-24T18:30:09+00:00 CRITICAL Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/StoreApi/Legacy.php:67 CONTEXT: {"error":{"type":1,"file":"/home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/StoreApi/Legacy.php","line":67},"backtrace":["","#0 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/StoreApi/Legacy.php(67): array_merge()","#1 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\StoreApi\Legacy->process_legacy_payment()","#2 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()","#3 /home/linknacional/paraquemdoar.org/wp-includes/plugin.php(565): WP_Hook->do_action()","#4 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/StoreApi/Utilities/CheckoutTrait.php(83): do_action_ref_array()","#5 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php(262): Automattic\WooCommerce\StoreApi\Routes\V1\Checkout->process_payment()","#6 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/StoreApi/Routes/V1/AbstractRoute.php(121): Automattic\WooCommerce\StoreApi\Routes\V1\Checkout->get_route_post_response()","#7 /home/linknacional/paraquemdoar.org/wp-content/plugins/woocommerce/src/StoreApi/Routes/V1/Checkout.php(135): Automattic\WooCommerce\StoreApi\Routes\V1\AbstractRoute->get_response_by_request_method()","#8 /home/linknacional/paraquemdoar.org/wp-includes/rest-api/class-wp-rest-server.php(1230): Automattic\WooCommerce\StoreApi\Routes\V1\Checkout->get_response()","#9 /home/linknacional/paraquemdoar.org/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request()","#10 /home/linknacional/paraquemdoar.org/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch()","#11 /home/linknacional/paraquemdoar.org/wp-includes/rest-api.php(420): WP_REST_Server->serve_request()","#12 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-hook.php(324): rest_api_loaded()","#13 /home/linknacional/paraquemdoar.org/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()","#14 /home/linknacional/paraquemdoar.org/wp-includes/plugin.php(565): WP_Hook->do_action()","#15 /home/linknacional/paraquemdoar.org/wp-includes/class-wp.php(418): do_action_ref_array()","#16 /home/linknacional/paraquemdoar.org/wp-includes/class-wp.php(813): WP->parse_request()","#17 /home/linknacional/paraquemdoar.org/wp-includes/functions.php(1336): WP->main()","#18 /home/linknacional/paraquemdoar.org/wp-blog-header.php(16): wp()","#19 /home/linknacional/paraquemdoar.org/index.php(17): require('/home/linknacio...')","#20 {main}","thrown"]}
```

**Comment by GuilhermeLinkNacional** [comment]
Corrigido
